# version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=myemployees
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myemployees-network

volumes:
  mysql-data:

networks:
  myemployees-network:
    driver: bridge